import { useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Play, Pause, X } from "lucide-react";
import type { PreviewTarget } from "@/components/PreviewPlayer";
import { useWorkspace } from "@/components/workspace/WorkspaceContext";
export function WaveformPlayer({target,resolve,onClose}:{target:PreviewTarget|null;resolve:(q:{artist?:string;title?:string;filePath?:string})=>File|undefined;onClose:()=>void}){
 const { ensureLocalFile } = useWorkspace();
 const resolved=useMemo(()=>target?resolve({artist:target.artist,title:target.song,filePath:target.filePath}):undefined,[target,resolve]);
 const [diskFile,setDiskFile]=useState<File|null>(null);
 // Desktop app: read the remembered file straight off disk when it isn't loaded.
 useEffect(()=>{let active=true;setDiskFile(null);if(!target||resolved)return;void ensureLocalFile(target.filePath).then(f=>{if(active)setDiskFile(f)});return()=>{active=false}},[target,resolved,ensureLocalFile]);
 const file=resolved??diskFile??undefined;
  const [url,setUrl]=useState<string|null>(null),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[duration,setDuration]=useState(0),[bars,setBars]=useState<number[]>([]);
 const audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>{if(!file){setUrl(null);setBars([]);return}const next=URL.createObjectURL(file);setUrl(next);setPlaying(false);setProgress(0);return()=>URL.revokeObjectURL(next)},[file]);
 useEffect(()=>{if(!file)return;let cancelled=false;const audioContext=new AudioContext();file.arrayBuffer().then(data=>audioContext.decodeAudioData(data)).then(decoded=>{if(cancelled)return;const samples=decoded.getChannelData(0);const count=100;const stride=Math.max(1,Math.floor(samples.length/count));setBars(Array.from({length:count},(_,i)=>{let peak=0;for(let j=i*stride;j<Math.min((i+1)*stride,samples.length);j+=Math.max(1,Math.floor(stride/200)))peak=Math.max(peak,Math.abs(samples[j]));return Math.max(8,Math.min(100,peak*100))}))}).catch(()=>{}).finally(()=>void audioContext.close());return()=>{cancelled=true}},[file]);
 if(!target)return null;
  const time=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,"0")}`;
  const seek=(fraction:number)=>{if(audio.current?.duration)audio.current.currentTime=Math.max(0,Math.min(1,fraction))*audio.current.duration};
  return <div className="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-card px-3 py-2 shadow-lg lg:left-56"><div className="flex w-full items-center gap-2 sm:gap-4"><Button size="icon" variant="secondary" className="shrink-0" disabled={!url} aria-label={playing?"Pause":"Play"} onClick={()=>{if(!audio.current)return;if(playing)audio.current.pause();else void audio.current.play()}}>{playing?<Pause size={18}/>:<Play size={18}/>}</Button><div className="hidden min-w-0 w-32 shrink-0 text-xs sm:block"><p className="truncate font-semibold">{target.song}</p><p className="truncate text-muted-foreground">{target.artist}</p></div><span className="hidden shrink-0 text-[11px] tabular-nums text-muted-foreground md:inline">{time(progress*duration)}</span><div className="min-w-0 flex-1"><div className="flex h-9 cursor-pointer items-center gap-px" role="slider" aria-label="Playback position" aria-valuenow={Math.round(progress*100)} aria-valuemin={0} aria-valuemax={100} tabIndex={0} onKeyDown={e=>{if(e.key==="ArrowRight")seek(progress+.05);if(e.key==="ArrowLeft")seek(progress-.05)}} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();seek((e.clientX-rect.left)/rect.width)}}>{(bars.length?bars:Array.from({length:100},()=>10)).map((h,i)=><span key={i} className={`min-w-px flex-1 rounded-sm ${i/100<progress?"bg-primary":"bg-muted-foreground/40"}`} style={{height:`${h}%`}}/>)}</div>{!url&&<p className="text-[11px] text-warning">Reconnect the music folder to play the actual file.</p>}</div><span className="hidden shrink-0 text-[11px] tabular-nums text-muted-foreground md:inline">{time(duration)}</span><Button size="icon" variant="ghost" className="shrink-0" aria-label="Close player" onClick={onClose}><X size={17}/></Button><audio ref={audio} src={url??undefined} onLoadedMetadata={e=>setDuration(e.currentTarget.duration||0)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={e=>setProgress(e.currentTarget.duration?e.currentTarget.currentTime/e.currentTarget.duration:0)} /></div></div>
}
